server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_category_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**
        - id: main_service_compilation_route
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
        - id: main_service_event_route
          uri: lb://main-service
          predicates:
            - Path=/events/**
        - id: main_service_user_route
          uri: lb://main-service
          predicates:
            - Path=/users/**
        - id: main_service_commentary_route
          uri: lb://main-service
          predicates:
            - Path=/comments/**
        - id: main_service_admin_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**