server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driverClassName: org.postgresql.Driver
    username: user
    password: user
    url: jdbc:postgresql://localhost:6552/user
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
    show_sql: 'true'
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/