CREATE TABLE IF NOT EXISTS participation_request (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(12) NOT NULL
);