server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**

        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**,/admin/categories/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/users/*/events/**,/events/**

        - id: location_service_route
          uri: lb://location-service
          predicates:
            - Path=//location/**

        - id: compilation_service_route
          uri: lb://compilation-service
          predicates:
            - Path=/compilations/**