server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      #routes:
      #  - id: main_service_route
      #    uri: lb://main-service
      #    predicates:
      #      - Path=/categories/**,/compilations/**,/events/**,/users/**,/comments/**,/admin/**
      routes:
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**,/admin/categories/**
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**