CREATE TABLE IF NOT EXISTS event (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  paid BOOLEAN DEFAULT FALSE,
  participant_limit INTEGER DEFAULT 0,
  confirmed_requests BIGINT DEFAULT 0,
  request_moderation BOOLEAN DEFAULT TRUE,
  title VARCHAR(120) NOT NULL,
  initiator_id BIGINT NOT NULL,
  state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_on TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  published_on TIMESTAMP WITH TIME ZONE,
  location_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title  varchar(50)
);
CREATE TABLE IF NOT EXISTS compilation_event (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_event_compilations
        FOREIGN KEY (compilation_id) REFERENCES compilations(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_compilation_event_event
        FOREIGN KEY (event_id) REFERENCES event(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);