grpc:
  server:
    port: 0

server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: stat
    password: stat
    url: jdbc:postgresql://localhost:6541/stat
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
    show_sql: 'true'
  sql:
    init:
      mode: always