server:
  port: 0

spring:
  application:
    name: stats-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: stat
    password: stat
    url: jdbc:postgresql://localhost:6541/stat
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    stat:
      server:
        service:
          StatServiceImpl: DEBUG
        repository:
          StatRepository: DEBUG