server:
  port: 0

spring:
  application:
    name: event-service
  datasource:
    driverClassName: org.postgresql.Driver
    username: event
    password: event
    url: jdbc:postgresql://localhost:6553/event
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
    show_sql: 'true'
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

grpc:
  server:
    enabled: false
    port: 0
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext